include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    unawaited_futures: error

linter:
  rules:
    unawaited_futures: true
    always_use_package_imports: true
    avoid_slow_async_io: true
    cancel_subscriptions: true
    close_sinks: true
    no_adjacent_strings_in_list: true
    use_build_context_synchronously: false
