name: uhf_devices
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://www.metratec.com

environment:
  sdk: '>=2.17.5 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies: {libserialport: ^0.3.0+1}
