name: reader_library
description: Implementation of Dart lib for Metratec UHF devices
version: 3.0.0
homepage: https://www.metratec.com

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  libserialport: ^0.3.0+1
  logger: ^1.4.0
  metratec_device:
    # path: ../metratec_device
    git:
      url: https://gitlab.metratec.com/dart-libraries/metratec_device.git
      ref: identifiable-device
  string_validator: ^0.3.0
  dart_rfid_utils:
#    path: ../dart_rfid_utils
    git:
      url: https://gitlab.metratec.com/dart-libraries/dart_rfid_utils.git
      # Error can not resolve HEAD
      ref: 6b07c1b8d09797cf0f9a4fb196364fc38bc44682