name: reader_library
description: Implementation of Dart lib for Metratec UHF devices
version: 3.0.0
homepage: https://www.metratec.com

publish_to: none

environment:
  sdk: '>=2.17.5 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  libserialport: ^0.3.0+1
  logger: ^1.4.0
  metratec_device:
    # path: ../metratec_device
    git:
      url: https://gitlab.metratec.com/dart-libraries/metratec_device.git
    #   ref: 1.1.0
  string_validator: ^0.3.0
