name: dart_rfid_library
description: Implementation of Dart lib for Metratec RFID devices
version: 2.1.1
homepage: https://www.metratec.com

publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^4.0.0
  test: ^1.16.0

dependencies:
  async: ^2.11.0
  collection: ^1.17.1
  #libserialport: ^0.3.0+1
  logger: ^2.0.2+1
  string_validator: ^0.3.0

  metratec_device:
    git:
     url: https://github.com/metratec/metratec_device.git
     ref: 3.3.1

  dart_rfid_utils:
    git:
      url: https://github.com/metratec/dart_rfid_utils.git
      ref: 1.0.0

# Path dependencies for development
#  metratec_device:
#    path: ../metratec_device
#  dart_rfid_utils:
#    path: ../dart_rfid_utils
