enum TagType {
  ISO15,
  MFC,
  MF_MINI,
  TagNPlay,
  MF_UL,
  MF_UL_EV1,
  MF_UL_C,
  MF_UL_NANO,
  MF_HOSPITALITY,
  NTAG_2XX,
  NTAG_4XX,
  MF_PLUS,
  MF_PLUS_EV1,
  MF_PLUS_EV2,
  MF_PLUS_S,
  MF_PLUS_X,
  MF_PLUS_SE,
  MF_DESFIRE_EV1,
  MF_DESFIRE_EV2,
  MF_DESFIRE_EV3,
  MF_DESFIRE_LIGHT,
  unknown;

  String get protocolString => name;

  String get displayName => switch (this) {
        ISO15 => "ISO15693",
        MFC => "Mifare Classic",
        MF_MINI => "Mifare Mini",
        TagNPlay => "Unknown",
        MF_UL => "Mifare Ultralight",
        MF_UL_EV1 => "Mifare Ultralight EV1",
        MF_UL_C => "Mifare Ultralight C",
        MF_UL_NANO => "Mifare Ultralight Nano",
        MF_HOSPITALITY => "Mifare Hospitality",
        NTAG_2XX => "Ntag 213/215/216",
        NTAG_4XX => "Ntag 424/426",
        MF_PLUS => "Mifare Plus",
        MF_PLUS_EV1 => "Mifare Plus EV1",
        MF_PLUS_EV2 => "Mifare Plus EV2",
        MF_PLUS_S => "Mifare Plus S",
        MF_PLUS_X => "Mifare Plus X",
        MF_PLUS_SE => "Mifare Plus SE",
        MF_DESFIRE_EV1 => "Mifare Desfire EV1",
        MF_DESFIRE_EV2 => "Mifare Desfire EV2",
        MF_DESFIRE_EV3 => "Mifare Desfire EV3",
        MF_DESFIRE_LIGHT => "Mifare Desfire Light",
        unknown => "Unknown",
      };
}
